/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.poly.ui;

import com.poly.utils.DialogHelPer;
import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author admin
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        init();
        chuChay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlNen = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblHoSo = new javax.swing.JLabel();
        lblTaoTaiKhoan = new javax.swing.JLabel();
        lblText = new javax.swing.JLabel();
        lblHuongdan = new javax.swing.JLabel();
        tblMain = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblQLSinhVien = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblQLLop = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblQLMonHoc = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lblQLKhoa = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lblQLGiangVien = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        lblQLDiemSV = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        lblQLThongKe = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel13 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblDoiMatKhau = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblThoat = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlNen.setBackground(new java.awt.Color(255, 255, 255));
        pnlNen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblHoSo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/account-circle.png"))); // NOI18N

        lblTaoTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/account-lock-open.png"))); // NOI18N
        lblTaoTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTaoTaiKhoanMouseClicked(evt);
            }
        });

        lblText.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        lblText.setForeground(new java.awt.Color(255, 51, 51));
        lblText.setText("Đừng bao giờ ngừng học tập vì cuộc đời không bao giờ ngừng dạy!!!");

        lblHuongdan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/alarm-light-outline.png"))); // NOI18N
        lblHuongdan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHuongdanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(lblHuongdan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTaoTaiKhoan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHoSo)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lblText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lblHoSo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTaoTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHuongdan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlNenLayout = new javax.swing.GroupLayout(pnlNen);
        pnlNen.setLayout(pnlNenLayout);
        pnlNenLayout.setHorizontalGroup(
            pnlNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tblMain)
        );
        pnlNenLayout.setVerticalGroup(
            pnlNenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNenLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tblMain, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE))
        );

        getContentPane().add(pnlNen, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 0, 670, 600));

        jPanel1.setBackground(new java.awt.Color(32, 33, 35));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(32, 33, 35));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });

        lblHome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHome.setForeground(new java.awt.Color(255, 255, 255));
        lblHome.setText("Home");
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/home-account.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHome, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 105, -1, 40));

        jPanel4.setBackground(new java.awt.Color(32, 33, 35));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQLSinhVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQLSinhVien.setForeground(new java.awt.Color(255, 255, 255));
        lblQLSinhVien.setText("Quản Lí Sinh Viên");
        lblQLSinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLSinhVienMouseClicked(evt);
            }
        });
        jPanel4.add(lblQLSinhVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 2, 160, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/account-edit.png"))); // NOI18N
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 10, 30, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 210, 40));

        jPanel5.setBackground(new java.awt.Color(32, 33, 35));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQLLop.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQLLop.setForeground(new java.awt.Color(255, 255, 255));
        lblQLLop.setText("Quản Lí Lớp");
        lblQLLop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLLopMouseClicked(evt);
            }
        });
        jPanel5.add(lblQLLop, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 11, 160, 21));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/google-classroom.png"))); // NOI18N
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 16, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 210, 40));

        jPanel6.setBackground(new java.awt.Color(32, 33, 35));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQLMonHoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQLMonHoc.setForeground(new java.awt.Color(255, 255, 255));
        lblQLMonHoc.setText("Quản Lí Môn Học");
        jPanel6.add(lblQLMonHoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 11, 160, 21));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/application-edit.png"))); // NOI18N
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 16, -1, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 210, 40));

        jPanel7.setBackground(new java.awt.Color(32, 33, 35));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQLKhoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQLKhoa.setForeground(new java.awt.Color(255, 255, 255));
        lblQLKhoa.setText("Quản Lí Khoa");
        lblQLKhoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLKhoaMouseClicked(evt);
            }
        });
        jPanel7.add(lblQLKhoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 11, 160, 21));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/book-education-outline.png"))); // NOI18N
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 16, -1, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 210, 40));

        jPanel10.setBackground(new java.awt.Color(32, 33, 35));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQLGiangVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQLGiangVien.setForeground(new java.awt.Color(255, 255, 255));
        lblQLGiangVien.setText("Quản Lí Giảng Viên");
        lblQLGiangVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLGiangVienMouseClicked(evt);
            }
        });
        jPanel10.add(lblQLGiangVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 11, 164, 21));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/camera-control.png"))); // NOI18N
        jPanel10.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 16, -1, -1));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 210, 40));

        jPanel11.setBackground(new java.awt.Color(32, 33, 35));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQLDiemSV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQLDiemSV.setForeground(new java.awt.Color(255, 255, 255));
        lblQLDiemSV.setText("Quản Lí Điểm ");
        lblQLDiemSV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQLDiemSVMouseClicked(evt);
            }
        });
        jPanel11.add(lblQLDiemSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 11, 164, 21));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/crown-outline.png"))); // NOI18N
        jPanel11.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 16, -1, -1));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 210, 40));

        jPanel12.setBackground(new java.awt.Color(32, 33, 35));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQLThongKe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblQLThongKe.setForeground(new java.awt.Color(255, 255, 255));
        lblQLThongKe.setText("Quản Lí Thống Kê");
        jPanel12.add(lblQLThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 11, 164, 21));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/database-arrow-up.png"))); // NOI18N
        jPanel12.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 16, -1, -1));

        jPanel1.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 210, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 180, -1));

        jPanel13.setBackground(new java.awt.Color(32, 33, 35));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/all-inclusive-box.png"))); // NOI18N
        jPanel13.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 16, -1, -1));

        lblDoiMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDoiMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        lblDoiMatKhau.setText("Đổi Mật Khẩu");
        lblDoiMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDoiMatKhauMouseClicked(evt);
            }
        });
        jPanel13.add(lblDoiMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 137, -1));

        jPanel1.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 210, 50));

        jPanel14.setBackground(new java.awt.Color(32, 33, 35));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/icons/power.png"))); // NOI18N
        jPanel14.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        lblThoat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblThoat.setForeground(new java.awt.Color(255, 255, 255));
        lblThoat.setText("Thoát");
        lblThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThoatMouseClicked(evt);
            }
        });
        jPanel14.add(lblThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 160, -1));

        jPanel1.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 210, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/poly/img/Capture.PNG"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblTaoTaiKhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTaoTaiKhoanMouseClicked

        taotaikhoan = new TaoTaiKhoan();
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/poly/icons/account-lock-open.png"));
        tblMain.addTab("Tạo Tài Khoản", icon, taotaikhoan, "Tạo Tài Khoản");

        tblMain.setSelectedComponent(taotaikhoan);


    }//GEN-LAST:event_lblTaoTaiKhoanMouseClicked

    private void lblThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThoatMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblThoatMouseClicked

    private void lblDoiMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDoiMatKhauMouseClicked

        doimatkhau = new DoiMatKhau();
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/poly/icons/all-inclusive-box.png"));
        tblMain.addTab("Đổi Mật Khẩu", icon, doimatkhau, "Đổi Mật Khẩu");

        tblMain.setSelectedComponent(doimatkhau);
    }//GEN-LAST:event_lblDoiMatKhauMouseClicked

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        tblMain.removeAll();
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblQLSinhVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLSinhVienMouseClicked
        qlsinhvien = new SinhVien();
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/poly/icons/all-inclusive-box.png"));
        tblMain.addTab("Quản Lí Sinh Viên", icon, qlsinhvien, "Quản Lí Sinh Viên");

        tblMain.setSelectedComponent(qlsinhvien);
    }//GEN-LAST:event_lblQLSinhVienMouseClicked

    private void lblQLGiangVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLGiangVienMouseClicked
        qlgiangvien = new GiangVien();
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/poly/icons/all-inclusive-box.png"));
        tblMain.addTab("Quản Giảng Viên", icon, qlgiangvien, "Quản Lí Giảng Viên");

        tblMain.setSelectedComponent(qlgiangvien);
    }//GEN-LAST:event_lblQLGiangVienMouseClicked

    private void lblQLDiemSVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLDiemSVMouseClicked
        qldiemsinhvien = new DiemSinhVien();
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/poly/icons/all-inclusive-box.png"));
        tblMain.addTab("Thông Tin Điểm Sinh Viên", icon, qldiemsinhvien, "Thông Tin Điểm Sinh Viên");

        tblMain.setSelectedComponent(qldiemsinhvien);
    }//GEN-LAST:event_lblQLDiemSVMouseClicked

    private void lblQLLopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLLopMouseClicked
        qllop = new Lop();
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/poly/icons/all-inclusive-box.png"));
        tblMain.addTab("Quản Lí Lớp", icon, qllop, "Quản Lí Lớp");

        tblMain.setSelectedComponent(qllop);
    }//GEN-LAST:event_lblQLLopMouseClicked

    private void lblQLKhoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQLKhoaMouseClicked
        qlkhoa = new Khoa();
        ImageIcon icon = new ImageIcon(getClass().getResource("/com/poly/icons/all-inclusive-box.png"));
        tblMain.addTab("Quản Lí Khoa", icon, qlkhoa, "Quản Lí Khoa");

        tblMain.setSelectedComponent(qlkhoa);
    }//GEN-LAST:event_lblQLKhoaMouseClicked

    private void lblHuongdanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHuongdanMouseClicked
        // TODO add your handling code here:
        try {

            Desktop.getDesktop().browse(new File("help/index.html").toURI());
        } catch (Exception e) {
            DialogHelPer.alert(this, "Không tìm thấy file hướng dẫn!");
        }
    }//GEN-LAST:event_lblHuongdanMouseClicked

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:
        jPanel3.setBackground(new Color(102,255,204));
        lblHome.setForeground(new Color(32,33,35));
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        // TODO add your handling code here:
        jPanel3.setBackground(new Color(32,33,35));
        lblHome.setForeground(Color.white);
    }//GEN-LAST:event_jPanel3MouseExited
    
    public void chuChay(){
        Thread thread1 = new Thread(){
            @Override
            public void run() {
                String txt = lblText.getText() + "       ";
                while(true){
                    txt = txt.substring(1, txt.length()) + txt.charAt(0);
//                      txt = txt.charAt(txt.length() -1) +   txt.substring(0, txt.length() - 1);
                    try {
                        sleep(100);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    lblText.setText(txt);
                }
            }
            
        };
        thread1.start();
    }
    void chao(){
        ChaoJDialog chao = new ChaoJDialog(this, true);
        chao.setVisible(true);
    }
    void logIn(){
        DangNhapJDialog login = new DangNhapJDialog(this, true);
        login.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDoiMatKhau;
    private javax.swing.JLabel lblHoSo;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblHuongdan;
    private javax.swing.JLabel lblQLDiemSV;
    private javax.swing.JLabel lblQLGiangVien;
    private javax.swing.JLabel lblQLKhoa;
    private javax.swing.JLabel lblQLLop;
    private javax.swing.JLabel lblQLMonHoc;
    private javax.swing.JLabel lblQLSinhVien;
    private javax.swing.JLabel lblQLThongKe;
    private javax.swing.JLabel lblTaoTaiKhoan;
    private javax.swing.JLabel lblText;
    private javax.swing.JLabel lblThoat;
    private javax.swing.JPanel pnlNen;
    private javax.swing.JTabbedPane tblMain;
    // End of variables declaration//GEN-END:variables

    private TaoTaiKhoan taotaikhoan;
    private DoiMatKhau doimatkhau;
    private SinhVien qlsinhvien;
    private GiangVien qlgiangvien;
    private DiemSinhVien qldiemsinhvien;
    private Lop qllop;
    private Khoa qlkhoa;
    private MonHoc qlmonhoc;
    private void init() {
        this.setLocationRelativeTo(null);
        chao();
        logIn();
    }
}
